NET/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NET.Models;

namespace NET.Controllers
{
    public class ClienteController : Controller
    {
        [Authorize]
        // GET: Cliente
        public ActionResult Index()
        {
            using (var db = new inventario2021Entities1())
            {
                return View(db.cliente.ToList());
            }
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(cliente cliente)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    db.cliente.Add(cliente);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }


        }
        public ActionResult Details(int id)
        {
            using (var db = new inventario2021Entities1())
            {
                var findCliente = db.cliente.Find(id);
                return View(findCliente);
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    var findCliente = db.cliente.Find(id);
                    db.cliente.Remove(findCliente);
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    cliente findCliente = db.cliente.Where(a => a.id == id).FirstOrDefault();
                    return View(findCliente);
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(cliente editCliente)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    cliente ente = db.cliente.Find(editCliente.id);
                    ente.nombre = editCliente.nombre;
                    ente.documento = editCliente.documento;
                    ente.email = editCliente.email;

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }

        }
        
    }
}

NET/Controllers/CompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NET.Models;

namespace NET.Controllers
{
    public class CompraController : Controller
    {
        [Authorize]
        // GET: Compra
        public ActionResult Index()
        {
            try
            {
                var db = new inventario2021Entities1();
                var query = from tabCliente in db.cliente
                            join tabUser in db.usuario on tabCliente.id equals tabUser.id
                            select new Compa
                            {
                                idUser = tabUser.nombre,
                                idCliente = tabCliente.nombre
                            };
                return View(query);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(compra compra)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    db.compra.Add(compra);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }


        }
        public ActionResult Details(int id)
        {
            using (var db = new inventario2021Entities1())
            {
                var findCo = db.compra.Find(id);
                return View(findCo);
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    var findCo = db.compra.Find(id);
                    db.compra.Remove(findCo);
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    compra findCo = db.compra.Where(a => a.id == id).FirstOrDefault();
                    return View(findCo);
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(compra editCo)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    compra compra = db.compra.Find(editCo.id);
                    compra.fecha = editCo.fecha;
                    compra.total = editCo.total;
                    compra.id_usuario = editCo.id_usuario;
                    compra.id_cliente = editCo.id_cliente;

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }

        }

    }
}

NET/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NET.Models;

namespace NET.Controllers
{
    public class RolesController : Controller
    {
        [Authorize]
        // GET: Roles
        public ActionResult Index()
        {
            using (var db = new inventario2021Entities1())
            {
                return View(db.roles.ToList());
            }
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(roles roles)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    db.roles.Add(roles);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }


        }
        public ActionResult Details(int id)
        {
            using (var db = new inventario2021Entities1())
            {
                var findRol = db.roles.Find(id);
                return View(findRol);
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    var findRol = db.roles.Find(id);
                    db.roles.Remove(findRol);
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                   roles findRol = db.roles.Where(a => a.id == id).FirstOrDefault();
                    return View(findRol);
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(roles Editro)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                  roles ente = db.roles.Find(Editro.id);
                    ente.descripcion = Editro.descripcion; 

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }

        }
    }
}

NET/Views/Shared/Paginador.cshtml
@model NET.Models.BaseModelo

@{
    var cantidadPaginas = (int)Math.Ceiling((double)Model.Total / Model.RecordsPage);
}

<ul>
    @if (Model.ActualPage == 1)
    {
        Model.valueQueryString["pagina"] = 1;
        <li class="disabled">@Html.ActionLink("Anterior", null, Model.valueQueryString)</li>
    }
    else
    {
        Model.valueQueryString["pagina"] = Model.ActualPage - 1;
        <li class="">@Html.ActionLink("Anterior", null, Model.valueQueryString)</li>
    }

    @if (Model.ActualPage == cantidadPaginas)
    {
        Model.valueQueryString["pagina"] = cantidadPaginas;
        <li class="disabled">@Html.ActionLink("Siguiente", null, Model.valueQueryString)</li>
    }
    else
    {
        Model.valueQueryString["pagina"] = Model.ActualPage + 1;
        <li class="">@Html.ActionLink("Siguiente", null, Model.valueQueryString)</li>
    }

</ul>

@{
    int Inicial = 1;
    var radio = 3;
    var cantidadMaximaDePaginas = radio * 2 - 1;
    int Final = (cantidadPaginas > cantidadMaximaDePaginas) ? cantidadMaximaDePaginas : cantidadPaginas;

    if (Model.ActualPage > radio + 1)
    {
        Inicial = Model.ActualPage - radio;

        if (cantidadPaginas > Model.ActualPage + radio)
        {
            Final = Model.ActualPage + radio;
        }
        else
        {
            Final = cantidadPaginas;
        }
    }

}

<ul class="pagination">
    @{Model.valueQueryString["pagina"] = 1; }

    <li>@Html.ActionLink("Primera", null, Model.valueQueryString)</li>
    @for (int i = Inicial; i <= Final; i++)
    {
        Model.valueQueryString["pagina"] = i;
        if (i == Model.ActualPage)
        {
            <li class="active">@Html.ActionLink(i.ToString(), null, Model.valueQueryString)</li>
        }
        else
        {
            <li>@Html.ActionLink(i.ToString(), null, Model.valueQueryString)</li>
        }
    }
    @{Model.valueQueryString["pagina"] = cantidadPaginas; }
    <li>@Html.ActionLink("Ultima", null, Model.valueQueryString)</li>
</ul>

NET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Software Inventario</title>


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Chettan+2&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bungee+Shade&display=swap" rel="stylesheet">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/Custom.css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Software Inventario", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Opciones
                            <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Usuario Crud", "Index", "Usuario")</li>
                            <li>@Html.ActionLink("Producto Crud", "Index", "Producto")</li>
                            <li>@Html.ActionLink("Proveedor Crud", "Index", "Proveedor")</li>
                            <li>@Html.ActionLink("Cliente Crud", "Index", "Cliente")</li>
                            <li>@Html.ActionLink("Roles Crud", "Index", "Roles")</li>
                            <li>@Html.ActionLink("Usuario-Rol Crud", "UsRol", "Usuariorol")</li>
                            <li>@Html.ActionLink("Compra Crud", "Index", "Compra")</li>
                            <li>@Html.ActionLink("ProductoCompra Crud", "Index", "ProductoCompra")</li>
                            <li>@Html.ActionLink("Cargar Imagen", "CargarImagen", "ProductoImagen")</li>
                            <li>@Html.ActionLink("Cargar CSV", "uploadCSV", "CargaCSV")</li>
                            <li>@Html.ActionLink("Reporte", "Reporte", "Producto")</li>
                            <li>@Html.ActionLink("Paginador", "PaginadorIndex", "Usuario")</li>


                        </ul>

                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Cerrar Sesion", "CloseSession", "Usuario")</li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hecho por: Juan Ducuara </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>